### ISSUE TITLE
[PUB] Allow range filtering for multiple fields

### ISSUE THREAD

**Issue by fako** [surfedushare/search-client#28]
Users would like to be able to filter on different fields like publisher_year and in the future modified_at.

Currently it's only possible to do range filtering for publisher_date. We would like that to be any amount of arbitrary fields, but it should be configured in the admin on the MetadataField model. Validation of the items of the filter should be appropriate for range filtering. 

In case of publisher_year we would like to filter both on specific items and on range. We need to think of a proper way how to allow for this.

**Comment by peterdubbeldsurf** [comment]
Deze kan (ook) worden gebruikt bij her-ingebruikname van het "Bijgewerkt op" Veld op de frontend van Publinova.

**Comment by fako** [comment]
Done
